# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:20:32+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, Field, constr


class AccountUsageRecordEnumGranularity(Enum):
    hourly = 'hourly'
    daily = 'daily'
    all = 'all'


class CommandEnumCommandMode(Enum):
    text = 'text'
    binary = 'binary'


class CommandEnumDirection(Enum):
    from_sim = 'from_sim'
    to_sim = 'to_sim'


class CommandEnumStatus(Enum):
    queued = 'queued'
    sent = 'sent'
    delivered = 'delivered'
    received = 'received'
    failed = 'failed'


class CommandEnumTransport(Enum):
    sms = 'sms'
    ip = 'ip'


class RatePlanEnumDataLimitStrategy(Enum):
    block = 'block'
    throttle = 'throttle'


class SimEnumResetStatus(Enum):
    resetting = 'resetting'


class SimEnumStatus(Enum):
    new = 'new'
    ready = 'ready'
    active = 'active'
    suspended = 'suspended'
    deactivated = 'deactivated'
    canceled = 'canceled'
    scheduled = 'scheduled'
    updating = 'updating'


class UsageRecordEnumGranularity(Enum):
    hourly = 'hourly'
    daily = 'daily'
    all = 'all'


class WirelessV1AccountUsageRecord(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the AccountUsageRecord resource.',
    )
    commands: Optional[Any] = Field(
        None,
        description='An object that describes the aggregated Commands usage for all SIMs during the specified period. See [Commands Usage Object](https://www.twilio.com/docs/wireless/api/account-usagerecord-resource#commands-usage-object).',
    )
    data: Optional[Any] = Field(
        None,
        description='An object that describes the aggregated Data usage for all SIMs over the period. See [Data Usage Object](https://www.twilio.com/docs/wireless/api/account-usagerecord-resource#data-usage-object).',
    )
    period: Optional[Any] = Field(
        None,
        description='The time period for which usage is reported. Contains `start` and `end` properties that describe the period using GMT date-time values specified in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )


class WirelessV1Command(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Command resource.',
    )
    command: Optional[str] = Field(
        None,
        description='The message being sent to or from the SIM. For text mode messages, this can be up to 160 characters. For binary mode messages, this is a series of up to 140 bytes of data encoded using base64.',
    )
    command_mode: Optional[CommandEnumCommandMode] = Field(
        None,
        description='The mode used to send the SMS message. Can be: `text` or `binary`. The default SMS mode is `text`.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )
    delivery_receipt_requested: Optional[bool] = Field(
        None, description='Whether to request a delivery receipt.'
    )
    direction: Optional[CommandEnumDirection] = Field(
        None,
        description='The direction of the Command. Can be `to_sim` or `from_sim`. The value of `to_sim` is synonymous with the term `mobile terminated`, and `from_sim` is synonymous with the term `mobile originated`.',
    )
    sid: Optional[
        constr(pattern=r'^DC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Command resource.',
    )
    sim_sid: Optional[
        constr(pattern=r'^DE[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Sim resource](https://www.twilio.com/docs/wireless/api/sim-resource) that the Command was sent to or from.',
    )
    status: Optional[CommandEnumStatus] = Field(
        None,
        description='The status of the Command. Can be: `queued`, `sent`, `delivered`, `received`, or `failed`. See [Status Values](https://www.twilio.com/docs/wireless/api/command-resource#status-values) for a description of each state.',
    )
    transport: Optional[CommandEnumTransport] = Field(
        None, description='The type of transport used. Can be: `sms` or `ip`.'
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class WirelessV1RatePlan(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the RatePlan resource.',
    )
    data_enabled: Optional[bool] = Field(
        None, description='Whether SIMs can use GPRS/3G/4G/LTE data connectivity.'
    )
    data_limit: Optional[int] = Field(
        None,
        description='The total data usage (download and upload combined) in Megabytes that the Network allows during one month on the home network (T-Mobile USA). The metering period begins the day of activation and ends on the same day in the following month. Can be up to 2TB.',
    )
    data_metering: Optional[str] = Field(
        None,
        description='The model used to meter data usage. Can be: `payg` and `quota-1`, `quota-10`, and `quota-50`. Learn more about the available [data metering models](https://www.twilio.com/docs/wireless/api/rateplan-resource#payg-vs-quota-data-plans).',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )
    friendly_name: Optional[str] = Field(
        None, description='The string that you assigned to describe the resource.'
    )
    international_roaming: Optional[List[str]] = Field(
        None,
        description='The list of services that SIMs capable of using GPRS/3G/4G/LTE data connectivity can use outside of the United States. Can contain: `data` and `messaging`.',
    )
    international_roaming_data_limit: Optional[int] = Field(
        None,
        description='The total data usage (download and upload combined) in Megabytes that the Network allows during one month when roaming outside the United States. Can be up to 2TB.',
    )
    messaging_enabled: Optional[bool] = Field(
        None,
        description='Whether SIMs can make, send, and receive SMS using [Commands](https://www.twilio.com/docs/wireless/api/command-resource).',
    )
    national_roaming_data_limit: Optional[int] = Field(
        None,
        description='The total data usage (download and upload combined) in Megabytes that the Network allows during one month on non-home networks in the United States. The metering period begins the day of activation and ends on the same day in the following month. Can be up to 2TB.',
    )
    national_roaming_enabled: Optional[bool] = Field(
        None,
        description='Whether SIMs can roam on networks other than the home network (T-Mobile USA) in the United States. See [national roaming](https://www.twilio.com/docs/wireless/api/rateplan-resource#national-roaming).',
    )
    sid: Optional[
        constr(pattern=r'^WP[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the RatePlan resource.',
    )
    unique_name: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.",
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')
    voice_enabled: Optional[bool] = Field(
        None, description='Deprecated. Whether SIMs can make and receive voice calls.'
    )


class CommandsCallbackMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class SmsFallbackMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class SmsMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class VoiceFallbackMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class VoiceMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class WirelessV1Sim(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) to which the Sim resource belongs.',
    )
    commands_callback_method: Optional[CommandsCallbackMethod] = Field(
        None,
        description='The HTTP method we use to call `commands_callback_url`.  Can be: `POST` or `GET`. Default is `POST`.',
    )
    commands_callback_url: Optional[AnyUrl] = Field(
        None,
        description='The URL we call using the `commands_callback_method` when the SIM originates a machine-to-machine [Command](https://www.twilio.com/docs/wireless/api/command-resource). Your server should respond with an HTTP status code in the 200 range; any response body will be ignored.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the Sim resource was last updated specified in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )
    e_id: Optional[str] = Field(None, description='Deprecated.')
    friendly_name: Optional[str] = Field(
        None, description='The string that you assigned to describe the Sim resource.'
    )
    iccid: Optional[str] = Field(
        None,
        description='The [ICCID](https://en.wikipedia.org/wiki/SIM_card#ICCID) associated with the SIM.',
    )
    ip_address: Optional[str] = Field(None, description='Deprecated.')
    links: Optional[Dict[str, Any]] = Field(
        None, description='The URLs of related subresources.'
    )
    rate_plan_sid: Optional[
        constr(pattern=r'^WP[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [RatePlan resource](https://www.twilio.com/docs/wireless/api/rateplan-resource) to which the Sim resource is assigned.',
    )
    reset_status: Optional[SimEnumResetStatus] = Field(
        None,
        description='The connectivity reset status of the SIM. Can be: null or `resetting`. When a connectivity reset is initiated on a SIM, this property is `resetting`. After the reset completes, it is null.',
    )
    sid: Optional[
        constr(pattern=r'^DE[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Sim resource.',
    )
    sms_fallback_method: Optional[SmsFallbackMethod] = Field(
        None, description='Deprecated.'
    )
    sms_fallback_url: Optional[AnyUrl] = Field(None, description='Deprecated.')
    sms_method: Optional[SmsMethod] = Field(None, description='Deprecated.')
    sms_url: Optional[AnyUrl] = Field(None, description='Deprecated.')
    status: Optional[SimEnumStatus] = Field(
        None,
        description='The status of the Sim resource. Can be: `new`, `ready`, `active`, `deactivated`, `canceled`, `deleted`, `scheduled`, or `updating`. See [Status Values](https://www.twilio.com/docs/wireless/api/sim-resource#status-values) for the description of each status.',
    )
    unique_name: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.",
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')
    voice_fallback_method: Optional[VoiceFallbackMethod] = Field(
        None,
        description='Deprecated. The HTTP method we use to call `voice_fallback_url`. Can be: `GET` or `POST`. Default is `POST`.',
    )
    voice_fallback_url: Optional[AnyUrl] = Field(
        None,
        description='Deprecated. The URL we call using the `voice_fallback_method` when an error occurs while retrieving or executing the TwiML requested from `voice_url`.',
    )
    voice_method: Optional[VoiceMethod] = Field(
        None,
        description='Deprecated. The HTTP method we use to call `voice_url`. Can be: `GET` or `POST`. Default is `POST`.',
    )
    voice_url: Optional[AnyUrl] = Field(
        None,
        description='Deprecated. The URL we call using the `voice_method` when the SIM-connected device makes a voice call.',
    )


class WirelessV1SimDataSession(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the DataSession resource.',
    )
    cell_id: Optional[str] = Field(
        None,
        description='The unique ID of the cellular tower that the device was attached to at the moment when the Data Session was last updated.',
    )
    cell_location_estimate: Optional[Any] = Field(
        None,
        description="An object that describes the estimated location in latitude and longitude where the device's Data Session took place. The location is derived from the `cell_id` when the Data Session was last updated. See [Cell Location Estimate Object](https://www.twilio.com/docs/wireless/api/datasession-resource#cell-location-estimate-object). ",
    )
    end: Optional[datetime] = Field(
        None,
        description='The date that the record ended, given as GMT in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )
    imei: Optional[str] = Field(
        None,
        description="The 'international mobile equipment identity' is the unique ID of the device using the SIM to connect. An IMEI is a 15-digit string: 14 digits for the device identifier plus a check digit calculated using the Luhn formula.",
    )
    last_updated: Optional[datetime] = Field(
        None,
        description='The date that the resource was last updated, given as GMT in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )
    operator_country: Optional[str] = Field(
        None,
        description="The three letter country code representing where the device's Data Session took place. This is determined by looking up the `operator_mcc`.",
    )
    operator_mcc: Optional[str] = Field(
        None,
        description="The 'mobile country code' is the unique ID of the home country where the Data Session took place. See: [MCC/MNC lookup](http://mcc-mnc.com/).",
    )
    operator_mnc: Optional[str] = Field(
        None,
        description="The 'mobile network code' is the unique ID specific to the mobile operator network where the Data Session took place.",
    )
    operator_name: Optional[str] = Field(
        None,
        description='The friendly name of the mobile operator network that the [SIM](https://www.twilio.com/docs/wireless/api/sim-resource)-connected device is attached to. This is determined by looking up the `operator_mnc`.',
    )
    packets_downloaded: Optional[int] = Field(
        None,
        description='The number of packets downloaded by the device between the `start` time and when the Data Session was last updated.',
    )
    packets_uploaded: Optional[int] = Field(
        None,
        description='The number of packets uploaded by the device between the `start` time and when the Data Session was last updated.',
    )
    radio_link: Optional[str] = Field(
        None,
        description='The generation of wireless technology that the device was using.',
    )
    sid: Optional[str] = Field(
        None,
        description='The unique string that we created to identify the DataSession resource.',
    )
    sim_sid: Optional[str] = Field(
        None,
        description='The SID of the [Sim resource](https://www.twilio.com/docs/wireless/api/sim-resource) that the Data Session is for.',
    )
    start: Optional[datetime] = Field(
        None,
        description='The date that the Data Session started, given as GMT in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )


class WirelessV1SimUsageRecord(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the UsageRecord resource.',
    )
    commands: Optional[Any] = Field(
        None,
        description="An object that describes the SIM's usage of Commands during the specified period. See [Commands Usage Object](https://www.twilio.com/docs/wireless/api/sim-usagerecord-resource#commands-usage-object).",
    )
    data: Optional[Any] = Field(
        None,
        description="An object that describes the SIM's data usage during the specified period. See [Data Usage Object](https://www.twilio.com/docs/wireless/api/sim-usagerecord-resource#data-usage-object).",
    )
    period: Optional[Any] = Field(
        None,
        description='The time period for which the usage is reported. Contains `start` and `end` datetime values given as GMT in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.',
    )
    sim_sid: Optional[str] = Field(
        None,
        description='The SID of the [Sim resource](https://www.twilio.com/docs/wireless/api/sim-resource) that this Usage Record is for.',
    )


class Meta(BaseModel):
    first_page_url: Optional[AnyUrl] = None
    key: Optional[str] = None
    next_page_url: Optional[AnyUrl] = None
    page: Optional[int] = None
    page_size: Optional[int] = None
    previous_page_url: Optional[AnyUrl] = None
    url: Optional[AnyUrl] = None


class V1CommandsGetResponse(BaseModel):
    commands: Optional[List[WirelessV1Command]] = None
    meta: Optional[Meta] = None


class CallbackMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class V1CommandsPostRequest(BaseModel):
    CallbackMethod_1: Optional[CallbackMethod] = Field(
        None,
        alias='CallbackMethod',
        description='The HTTP method we use to call `callback_url`. Can be: `POST` or `GET`, and the default is `POST`.',
    )
    CallbackUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we call using the `callback_url` when the Command has finished sending, whether the command was delivered or it failed.',
    )
    Command: str = Field(
        ...,
        description='The message body of the Command. Can be plain text in text mode or a Base64 encoded byte string in binary mode.',
    )
    CommandMode: Optional[CommandEnumCommandMode] = Field(
        None,
        description='The mode to use when sending the SMS message. Can be: `text` or `binary`. The default SMS mode is `text`.',
    )
    DeliveryReceiptRequested: Optional[bool] = Field(
        None,
        description="Whether to request delivery receipt from the recipient. For Commands that request delivery receipt, the Command state transitions to 'delivered' once the server has received a delivery receipt from the device. The default value is `true`.",
    )
    IncludeSid: Optional[str] = Field(
        None,
        description='Whether to include the SID of the command in the message body. Can be: `none`, `start`, or `end`, and the default behavior is `none`. When sending a Command to a SIM in text mode, we can automatically include the SID of the Command in the message body, which could be used to ensure that the device does not process the same Command more than once.  A value of `start` will prepend the message with the Command SID, and `end` will append it to the end, separating the Command SID from the message body with a space. The length of the Command SID is included in the 160 character limit so the SMS body must be 128 characters or less before the Command SID is included.',
    )
    Sim: Optional[str] = Field(
        None,
        description='The `sid` or `unique_name` of the [SIM](https://www.twilio.com/docs/wireless/api/sim-resource) to send the Command to.',
    )


class V1RatePlansGetResponse(BaseModel):
    meta: Optional[Meta] = None
    rate_plans: Optional[List[WirelessV1RatePlan]] = None


class V1RatePlansPostRequest(BaseModel):
    DataEnabled: Optional[bool] = Field(
        None, description='Whether SIMs can use GPRS/3G/4G/LTE data connectivity.'
    )
    DataLimit: Optional[int] = Field(
        None,
        description='The total data usage (download and upload combined) in Megabytes that the Network allows during one month on the home network (T-Mobile USA). The metering period begins the day of activation and ends on the same day in the following month. Can be up to 2TB and the default value is `1000`.',
    )
    DataMetering: Optional[str] = Field(
        None,
        description='The model used to meter data usage. Can be: `payg` and `quota-1`, `quota-10`, and `quota-50`. Learn more about the available [data metering models](https://www.twilio.com/docs/wireless/api/rateplan-resource#payg-vs-quota-data-plans).',
    )
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the resource. It does not have to be unique.',
    )
    InternationalRoaming: Optional[List[str]] = Field(
        None,
        description='The list of services that SIMs capable of using GPRS/3G/4G/LTE data connectivity can use outside of the United States. Can contain: `data` and `messaging`.',
    )
    InternationalRoamingDataLimit: Optional[int] = Field(
        None,
        description='The total data usage (download and upload combined) in Megabytes that the Network allows during one month when roaming outside the United States. Can be up to 2TB.',
    )
    MessagingEnabled: Optional[bool] = Field(
        None,
        description='Whether SIMs can make, send, and receive SMS using [Commands](https://www.twilio.com/docs/wireless/api/command-resource).',
    )
    NationalRoamingDataLimit: Optional[int] = Field(
        None,
        description='The total data usage (download and upload combined) in Megabytes that the Network allows during one month on non-home networks in the United States. The metering period begins the day of activation and ends on the same day in the following month. Can be up to 2TB. See [national roaming](https://www.twilio.com/docs/wireless/api/rateplan-resource#national-roaming) for more info.',
    )
    NationalRoamingEnabled: Optional[bool] = Field(
        None,
        description='Whether SIMs can roam on networks other than the home network (T-Mobile USA) in the United States. See [national roaming](https://www.twilio.com/docs/wireless/api/rateplan-resource#national-roaming).',
    )
    UniqueName: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.",
    )
    VoiceEnabled: Optional[bool] = Field(None, description='Deprecated.')


class V1RatePlansSidPostRequest(BaseModel):
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the resource. It does not have to be unique.',
    )
    UniqueName: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.",
    )


class V1SimsGetResponse(BaseModel):
    meta: Optional[Meta] = None
    sims: Optional[List[WirelessV1Sim]] = None


class V1SimsSidPostRequest(BaseModel):
    AccountSid: Optional[str] = Field(
        None,
        description="The SID of the [Account](https://www.twilio.com/docs/iam/api/account) to which the Sim resource should belong. The Account SID can only be that of the requesting Account or that of a [Subaccount](https://www.twilio.com/docs/iam/api/subaccounts) of the requesting Account. Only valid when the Sim resource's status is `new`. For more information, see the [Move SIMs between Subaccounts documentation](https://www.twilio.com/docs/wireless/api/sim-resource#move-sims-between-subaccounts).",
    )
    CallbackMethod_1: Optional[CallbackMethod] = Field(
        None,
        alias='CallbackMethod',
        description='The HTTP method we should use to call `callback_url`. Can be: `POST` or `GET`. The default is `POST`.',
    )
    CallbackUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we should call using the `callback_url` when the SIM has finished updating. When the SIM transitions from `new` to `ready` or from any status to `deactivated`, we call this URL when the status changes to an intermediate status (`ready` or `deactivated`) and again when the status changes to its final status (`active` or `canceled`).',
    )
    CommandsCallbackMethod_1: Optional[CommandsCallbackMethod] = Field(
        None,
        alias='CommandsCallbackMethod',
        description='The HTTP method we should use to call `commands_callback_url`. Can be: `POST` or `GET`. The default is `POST`.',
    )
    CommandsCallbackUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we should call using the `commands_callback_method` when the SIM sends a [Command](https://www.twilio.com/docs/wireless/api/command-resource). Your server should respond with an HTTP status code in the 200 range; any response body is ignored.',
    )
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the Sim resource. It does not need to be unique.',
    )
    RatePlan: Optional[str] = Field(
        None,
        description='The SID or unique name of the [RatePlan resource](https://www.twilio.com/docs/wireless/api/rateplan-resource) to which the Sim resource should be assigned.',
    )
    ResetStatus: Optional[SimEnumResetStatus] = Field(
        None,
        description='Initiate a connectivity reset on the SIM. Set to `resetting` to initiate a connectivity reset on the SIM. No other value is valid.',
    )
    SmsFallbackMethod_1: Optional[SmsFallbackMethod] = Field(
        None,
        alias='SmsFallbackMethod',
        description='The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`. Default is `POST`.',
    )
    SmsFallbackUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we should call using the `sms_fallback_method` when an error occurs while retrieving or executing the TwiML requested from `sms_url`.',
    )
    SmsMethod_1: Optional[SmsMethod] = Field(
        None,
        alias='SmsMethod',
        description='The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`. Default is `POST`.',
    )
    SmsUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we should call using the `sms_method` when the SIM-connected device sends an SMS message that is not a [Command](https://www.twilio.com/docs/wireless/api/command-resource).',
    )
    Status: Optional[SimEnumStatus] = Field(
        None,
        description='The new status of the Sim resource. Can be: `ready`, `active`, `suspended`, or `deactivated`.',
    )
    UniqueName: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the resource. It can be used in place of the `sid` in the URL path to address the resource.',
    )
    VoiceFallbackMethod_1: Optional[VoiceFallbackMethod] = Field(
        None, alias='VoiceFallbackMethod', description='Deprecated.'
    )
    VoiceFallbackUrl: Optional[AnyUrl] = Field(None, description='Deprecated.')
    VoiceMethod_1: Optional[VoiceMethod] = Field(
        None, alias='VoiceMethod', description='Deprecated.'
    )
    VoiceUrl: Optional[AnyUrl] = Field(None, description='Deprecated.')


class V1SimsSimSidDataSessionsGetResponse(BaseModel):
    data_sessions: Optional[List[WirelessV1SimDataSession]] = None
    meta: Optional[Meta] = None


class V1SimsSimSidUsageRecordsGetResponse(BaseModel):
    meta: Optional[Meta] = None
    usage_records: Optional[List[WirelessV1SimUsageRecord]] = None


class V1UsageRecordsGetResponse(BaseModel):
    meta: Optional[Meta] = None
    usage_records: Optional[List[WirelessV1AccountUsageRecord]] = None
